# Generated by Django 3.1.4 on 2020-12-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('al', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_clase', models.DateField()),
                ('hora_ini', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('extras', models.CharField(max_length=800)),
                ('asis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('periodo', models.CharField(max_length=30)),
                ('yr', models.DateField()),
                ('cla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('mat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.materia')),
            ],
        ),
    ]
