# Generated by Django 3.1.4 on 2020-12-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201206_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='fecha_creacion',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='mat',
            new_name='materia',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='asis',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='cla',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='clase',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.clase'),
        ),
        migrations.AddField(
            model_name='clase',
            name='grupo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='clase',
            name='materia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.materia'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='clase',
            name='dias_clase',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='materia',
            name='periodo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='materia',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
